# Generated by Django 4.2.30 on 2026-06-15 07:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Prod VPS 1, Dev Server', max_length=100, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=5432)),
                ('root_user', models.CharField(default='postgres', max_length=100)),
                ('root_password', models.CharField(max_length=255)),
                ('environment_type', models.CharField(choices=[('dev', 'Development'), ('prod', 'Production')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('db_name', models.CharField(max_length=63, unique=True)),
                ('db_user', models.CharField(max_length=63, unique=True)),
                ('db_password_temp', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('available', 'Available'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='provisioning', max_length=20)),
                ('created_by_sso_id', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='databases', to='api.product')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='api.databaseserver')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_path', models.CharField(help_text='Path in secure storage', max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='api.databaseinstance')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProductAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sso_user_id', models.CharField(help_text='The ID or username from Rubix SSO', max_length=255)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('developer', 'Developer'), ('admin', 'Admin')], max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.product')),
            ],
            options={
                'unique_together': {('sso_user_id', 'product')},
            },
        ),
    ]
