# Generated by Django 4.2.24 on 2025-09-13 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('student_username', models.CharField(max_length=150)),
                ('db_name', models.CharField(max_length=63, unique=True)),
                ('db_user', models.CharField(max_length=63, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('error', 'Error')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
