# Generated by Django 4.2.30 on 2026-06-16 09:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageBucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bucket_name', models.CharField(max_length=63, unique=True)),
                ('access_key', models.CharField(max_length=100)),
                ('secret_key', models.CharField(max_length=255)),
                ('endpoint', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('available', 'Available'), ('failed', 'Failed')], default='provisioning', max_length=20)),
                ('created_by_sso_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buckets', to='api.product')),
            ],
        ),
    ]
