# Generated by Django 4.2.24 on 2025-09-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaserequest',
            name='db_password_temp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
