# Generated by Django 4.2.30 on 2026-06-16 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_storagebucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebucket',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buckets', to='api.databaseserver'),
        ),
    ]
