# Generated by Django 4.2.24 on 2025-09-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_databaserequest_db_password_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaserequest',
            name='college_id',
            field=models.CharField(db_index=True, default='temp_college', max_length=100),
            preserve_default=False,
        ),
    ]
