# Generated by Django 4.2.30 on 2026-07-15 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_systemalert_alter_databaseserver_environment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_fingerprint', models.CharField(blank=True, max_length=64, null=True)),
                ('expected_fingerprint', models.CharField(blank=True, max_length=64, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('stale_alerted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeat', to='api.databaseinstance')),
            ],
        ),
    ]
