# Generated by Django 4.2.30 on 2026-07-18 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_instanceheartbeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('founding_engineer', 'Founding Engineer'), ('system', 'System/Celery'), ('script', 'Maintenance Script')], default='system', max_length=30)),
                ('actor', models.CharField(help_text="username / 'system' / script name", max_length=255)),
                ('action', models.CharField(choices=[('provision_db', 'Provision DB'), ('delete_db', 'Delete DB'), ('soft_delete_db', 'Soft Delete DB'), ('restore_db', 'Restore DB'), ('replicate_db', 'Replicate DB'), ('backup_db', 'Backup DB'), ('backup_failed', 'Backup Failed'), ('liveness_check', 'Liveness Check'), ('liveness_changed', 'Liveness Changed'), ('provision_bucket', 'Provision Bucket'), ('delete_bucket', 'Delete Bucket'), ('execute_query', 'Execute Query'), ('login', 'Login')], max_length=30)),
                ('target', models.CharField(help_text='db_name / bucket_name / instance id', max_length=255)),
                ('server', models.CharField(blank=True, max_length=255, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
