# Generated by Django 4.2.30 on 2026-07-19 13:41

import api.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('db_dump', 'Database Dump'), ('minio_media', 'MinIO Media Mirror'), ('db_copy_tb', 'DB Copy to TB Disk')], max_length=20)),
                ('target', models.CharField(help_text="db_name or bucket_name or 'all'", max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('items_total', models.IntegerField(default=0)),
                ('items_ok', models.IntegerField(default=0)),
                ('items_failed', models.IntegerField(default=0)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('destination', models.CharField(blank=True, help_text='e.g. /backups_media/minio/granth-production-media', max_length=500, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterField(
            model_name='databaseinstance',
            name='db_password_temp',
            field=api.models.EncryptedCharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='databaseserver',
            name='root_password',
            field=api.models.EncryptedCharField(help_text='Encrypted at rest (Fernet). Decrypted transparently on access.', max_length=512),
        ),
        migrations.AlterField(
            model_name='storagebucket',
            name='secret_key',
            field=api.models.EncryptedCharField(max_length=512),
        ),
    ]
