# Generated by Django 4.2.30 on 2026-07-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_backup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinstance',
            name='backup_enabled',
            field=models.BooleanField(default=True, help_text="Whether Nidhi's backup control plane backs this up. Prod defaults on; dev defaults off (opt-in via UI)."),
        ),
        migrations.AddField(
            model_name='storagebucket',
            name='backup_enabled',
            field=models.BooleanField(default=True, help_text="Whether Nidhi's backup control plane mirrors this bucket. Prod defaults on; dev defaults off (opt-in via UI)."),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('provision_db', 'Provision DB'), ('delete_db', 'Delete DB'), ('soft_delete_db', 'Soft Delete DB'), ('restore_db', 'Restore DB'), ('replicate_db', 'Replicate DB'), ('backup_db', 'Backup DB'), ('backup_failed', 'Backup Failed'), ('liveness_check', 'Liveness Check'), ('liveness_changed', 'Liveness Changed'), ('provision_bucket', 'Provision Bucket'), ('delete_bucket', 'Delete Bucket'), ('replicate_bucket', 'Replicate Bucket'), ('execute_query', 'Execute Query'), ('login', 'Login')], max_length=30),
        ),
        migrations.AlterField(
            model_name='backupstatus',
            name='kind',
            field=models.CharField(choices=[('db_dump', 'Database Dump'), ('minio_media', 'MinIO Media Mirror'), ('db_copy_tb', 'DB Copy to TB Disk'), ('bucket_replica', 'Bucket Replication')], max_length=20),
        ),
    ]
