# Generated by Django 4.2.30 on 2026-07-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_databaseinstance_backup_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(help_text='e.g. vitharn, aacharya, nova, ebooks, rubix', max_length=64, unique=True)),
                ('image', models.CharField(help_text='ghcr.io/vitharn-hq/<app>:latest', max_length=255)),
                ('last_latest_digest', models.CharField(blank=True, max_length=64, null=True)),
                ('last_latest_seen_at', models.DateTimeField(blank=True, help_text='When this :latest digest was first observed', null=True)),
                ('last_deployed_digest', models.CharField(blank=True, help_text='Digest we last confirmed the VPS is running', max_length=64, null=True)),
                ('last_deployed_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('last_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('stale_alerted', models.BooleanField(default=False)),
            ],
        ),
    ]
